export const previewNotifications = [
  {
    id: "notification-booking-pending",
    type: "facility_request",
    message: "Your booking request for Badminton Court A is pending staff review.",
    status_context: "pending",
    reference_id: "REQ-20260421-001",
    is_read: false,
    created_at: "2026-04-21 18:15",
    facility_name: "Badminton Court A",
    facility_type: "Badminton",
    booking_date: "2026-04-26",
    start_time: "18:00",
    end_time: "19:00",
    activity_description: "Weekly friendly doubles match with two invited club partners.",
    staff_response: "",
    attendees: 4,
    participants: ["Alex M.", "Emma W.", "Jason Lee", "Sarah Chen"],
  },
  {
    id: "notification-booking-accepted",
    type: "facility_request",
    message: "Your booking for Tennis Court A has been approved.",
    status_context: "accepted",
    reference_id: "REQ-20260420-002",
    is_read: false,
    created_at: "2026-04-21 16:40",
    facility_name: "Tennis Court A",
    facility_type: "Tennis",
    booking_date: "2026-04-24",
    start_time: "09:00",
    end_time: "10:00",
    activity_description: "Morning singles training session.",
    staff_response: "Approved. Please arrive 10 minutes before the start time.",
    attendees: 2,
    participants: ["Alex M.", "Emma W."],
  },
  {
    id: "notification-booking-rejected",
    type: "facility_request",
    message: "Your booking request for Swimming Pool Lane 2 was rejected.",
    status_context: "rejected",
    reference_id: "REQ-20260418-004",
    is_read: true,
    created_at: "2026-04-20 11:25",
    facility_name: "Swimming Pool Lane 2",
    facility_type: "Swimming",
    booking_date: "2026-04-23",
    start_time: "10:00",
    end_time: "11:00",
    activity_description: "Lane training for two members.",
    staff_response: "Rejected because the lane is reserved for a school programme.",
    attendees: 2,
    participants: ["Alex M.", "Jason Lee"],
  },
  {
    id: "notification-booking-cancelled",
    type: "facility_request",
    message: "Your upcoming booking for Badminton Court C has been cancelled.",
    status_context: "cancelled",
    reference_id: "REQ-20260416-006",
    is_read: true,
    created_at: "2026-04-19 09:30",
    facility_name: "Badminton Court C",
    facility_type: "Badminton",
    booking_date: "2026-04-22",
    start_time: "20:00",
    end_time: "21:00",
    activity_description: "Casual evening practice with friends.",
    staff_response: "Cancelled after the member requested a late withdrawal.",
    attendees: 3,
    participants: ["Alex M.", "Emma W.", "David K."],
  },
  {
    id: "notification-repair-pending",
    type: "repair_report",
    message: "Your repair ticket for Basketball Court B has been recorded.",
    status_context: "pending",
    reference_id: "REP-20260418-003",
    is_read: false,
    created_at: "2026-04-21 14:12",
    facility_name: "Basketball Court B",
    facility_type: "Basketball",
    repair_time: "2026-04-21 14:12",
    repair_description: "One of the portable scoreboards is not powering on during court use.",
    faulty_parts: ["equipment"],
  },
  {
    id: "notification-repair-resolved",
    type: "repair_report",
    message: "Your repair ticket for Swimming Pool Lane 2 has been resolved.",
    status_context: "resolved",
    reference_id: "REP-20260420-002",
    is_read: true,
    created_at: "2026-04-20 15:05",
    facility_name: "Swimming Pool Lane 2",
    facility_type: "Swimming",
    repair_time: "2026-04-20 15:05",
    repair_description: "The lane rope was detached and needed to be secured again.",
    faulty_parts: ["equipment", "surface"],
  },
  {
    id: "notification-match-pending",
    type: "match_request",
    message: "Alex M. sent you a new partner request.",
    status_context: "pending",
    reference_id: "MATCH-20260421-001",
    is_read: false,
    created_at: "2026-04-21 19:10",
    actor_name: "Alex M.",
    apply_description:
      "Would you like to play badminton on Saturday evening? I am looking for a consistent weekend partner.",
    respond_message: "",
    actor_bio: "Intermediate player looking for steady weekend badminton sessions.",
    actor_interests: ["Badminton", "Tennis"],
    actor_availability: ["Saturday Evening", "Sunday Morning"],
  },
  {
    id: "notification-match-accepted",
    type: "match_request",
    message: "Emma W. accepted your partner request.",
    status_context: "accepted",
    reference_id: "MATCH-20260420-002",
    is_read: false,
    created_at: "2026-04-21 12:20",
    actor_name: "Emma W.",
    apply_description: "I would love to train together after work on weekdays.",
    respond_message: "Sounds good. Let's start with next Monday evening.",
    actor_bio: "Yoga and tennis member looking to ease back into regular training.",
    actor_interests: ["Tennis", "Yoga"],
    actor_availability: ["Monday Evening", "Thursday Evening"],
  },
  {
    id: "notification-match-invalidated",
    type: "match_request",
    message: "Your request to Jason Lee has expired because matching was turned off.",
    status_context: "invalidated",
    reference_id: "MATCH-20260419-003",
    is_read: true,
    created_at: "2026-04-19 18:45",
    actor_name: "Jason Lee",
    apply_description: "Would you be free for table tennis this Friday evening?",
    respond_message: "Automatically invalidated because matching was closed.",
    actor_bio: "Competitive table tennis player who prefers quick evening sessions.",
    actor_interests: ["Table Tennis", "Badminton"],
    actor_availability: ["Friday Evening", "Saturday Afternoon"],
  },
  {
    id: "notification-friend-removed",
    type: "friend",
    message: "Emma W. removed you from their friends list.",
    status_context: "removed",
    reference_id: "preview-emma",
    is_read: false,
    created_at: "2026-04-21 09:05",
    actor_name: "Emma W.",
    respond_message: "",
    actor_bio: "Yoga and tennis member looking to ease back into regular training.",
    actor_interests: ["Tennis", "Yoga"],
    actor_availability: ["Monday Evening", "Thursday Evening"],
  },
];
