export const previewStaffActor = {
  id: "preview-staff-david",
  name: "David Chen",
  role: "Staff",
  createdAt: "2021-09-01",
};

export const previewStaffRequests = [
  {
    id: "REQ-1001",
    facilityId: "facility-badminton-a",
    facilityName: "Badminton Court A",
    facilityType: "Badminton",
    applicantName: "Alex M.",
    attendees: 4,
    activityDescription:
      "Friendly match between colleagues. We need the court for a small team building session and would like to keep all invited players on the same court.",
    status: "pending",
    date: "2026-04-15",
    startTime: "09:00",
    endTime: "11:00",
    submittedAt: "2026-04-10 14:30",
    participantNames: ["Emma W.", "Jason Lee", "Sarah C."],
    completedAt: "",
    conflictState: "available",
    conflictTitle: "Facility Available",
    conflictMessage: "No conflicting bookings for this time slot.",
  },
  {
    id: "REQ-1003",
    facilityId: "facility-badminton-a",
    facilityName: "Badminton Court A",
    facilityType: "Badminton",
    applicantName: "Mia Turner",
    attendees: 4,
    activityDescription: "Evening badminton doubles training block for a local league team.",
    status: "accepted",
    date: "2026-04-12",
    startTime: "17:00",
    endTime: "18:00",
    submittedAt: "2026-04-08 09:20",
    participantNames: ["Olivia B.", "Noah H.", "Liam G."],
    completedAt: "2026-04-09 10:35",
    conflictState: "available",
    conflictTitle: "Facility Available",
    conflictMessage: "This request was approved successfully and is now read-only on the staff requests page.",
  },
  {
    id: "REQ-1006",
    facilityId: "facility-swimming-2",
    facilityName: "Swimming Pool Lane 2",
    facilityType: "Swimming",
    applicantName: "Grace Lin",
    attendees: 1,
    activityDescription: "Private swim endurance session that had to be declined because the requested lane was reserved for maintenance training.",
    status: "rejected",
    date: "2026-04-08",
    startTime: "08:00",
    endTime: "09:00",
    submittedAt: "2026-04-07 18:20",
    participantNames: [],
    completedAt: "2026-04-07 19:15",
    conflictState: "conflict",
    conflictTitle: "Time Conflict Detected",
    conflictMessage: "This request was rejected because the requested slot could not be approved.",
  },
  {
    id: "REQ-1004",
    facilityId: "facility-tennis-b",
    facilityName: "Tennis Court B",
    facilityType: "Tennis",
    applicantName: "Ben Cooper",
    attendees: 2,
    activityDescription: "Tennis coaching session needing a nearby alternative because the first slot overlaps with an event.",
    status: "alternative suggested",
    date: "2026-04-11",
    startTime: "14:00",
    endTime: "15:00",
    submittedAt: "2026-04-07 16:40",
    participantNames: [],
    completedAt: "2026-04-08 09:10",
    conflictState: "conflict",
    conflictTitle: "Time Conflict Detected",
    conflictMessage: "The requested slot is no longer available, so this request was returned with an alternative.",
  },
  {
    id: "REQ-1005",
    facilityId: "facility-basketball-c",
    facilityName: "Basketball Court C",
    facilityType: "Basketball",
    applicantName: "Ryan Foster",
    attendees: 6,
    activityDescription: "Inter-office scrimmage booking request that was approved first, but the member later cancelled it.",
    status: "cancelled",
    date: "2026-04-09",
    startTime: "19:00",
    endTime: "20:30",
    submittedAt: "2026-04-06 12:15",
    participantNames: ["Ethan W.", "Mila T."],
    completedAt: "2026-04-06 16:05",
    conflictState: "conflict",
    conflictTitle: "Request Cancelled",
    conflictMessage: "This request is no longer active because it was cancelled.",
  },
];

export const previewStaffCheckIns = [
  {
    id: "REQ-2201",
    facilityId: "facility-badminton-a",
    facilityName: "Badminton Court A",
    facilityType: "Badminton",
    memberName: "Alex M.",
    attendees: 4,
    date: "2026-04-22",
    startTime: "18:00",
    endTime: "20:00",
    status: "accepted",
    participantNames: ["Emma W.", "Jason Lee", "Sarah C."],
    history: ["Approved by staff at 10:30 AM"],
    statusTitle: "Ready for Check-in",
    statusMessage: "The member has arrived within the valid time window.",
  },
  {
    id: "REQ-2202",
    facilityId: "facility-tennis-b",
    facilityName: "Tennis Court B",
    facilityType: "Tennis",
    memberName: "David K.",
    attendees: 2,
    date: "2026-04-22",
    startTime: "21:00",
    endTime: "22:30",
    status: "in_progress",
    participantNames: [],
    history: ["Approved by staff at 4:10 PM", "Check-in confirmed at 8:47 PM"],
    statusTitle: "Session in Progress",
    statusMessage: "This session has already been checked in.",
  },
  {
    id: "REQ-2203",
    facilityId: "facility-yoga-1",
    facilityName: "Yoga Studio 1",
    facilityType: "Yoga",
    memberName: "Sarah Chen",
    attendees: 1,
    date: "2026-04-22",
    startTime: "14:00",
    endTime: "16:00",
    status: "no_show",
    participantNames: [],
    history: ["Approved by staff at 9:05 AM", "The check-in window expired before arrival was confirmed."],
    statusTitle: "No-show",
    statusMessage: "This booking missed the valid check-in window and can no longer be confirmed.",
  },
];
